import './globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'Vrutti | Livelihood Impact Partners',
  description: 'Generated by vruttiimpactcatalysts.org',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></Script>
        {children}</body>
    </html>
  )
}
